/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteRouteImport } from './routes/products/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsAddRouteRouteImport } from './routes/products/add/route'
import { Route as ProductsEditIdRouteRouteImport } from './routes/products/edit/$id/route'
import { Route as ProductsDetailsIdRouteRouteImport } from './routes/products/details/$id/route'

const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsAddRouteRoute = ProductsAddRouteRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsEditIdRouteRoute = ProductsEditIdRouteRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsDetailsIdRouteRoute = ProductsDetailsIdRouteRouteImport.update({
  id: '/details/$id',
  path: '/details/$id',
  getParentRoute: () => ProductsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsRouteRouteWithChildren
  '/products/add': typeof ProductsAddRouteRoute
  '/products/': typeof ProductsIndexRoute
  '/products/details/$id': typeof ProductsDetailsIdRouteRoute
  '/products/edit/$id': typeof ProductsEditIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/add': typeof ProductsAddRouteRoute
  '/products': typeof ProductsIndexRoute
  '/products/details/$id': typeof ProductsDetailsIdRouteRoute
  '/products/edit/$id': typeof ProductsEditIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products': typeof ProductsRouteRouteWithChildren
  '/products/add': typeof ProductsAddRouteRoute
  '/products/': typeof ProductsIndexRoute
  '/products/details/$id': typeof ProductsDetailsIdRouteRoute
  '/products/edit/$id': typeof ProductsEditIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/products/add'
    | '/products/'
    | '/products/details/$id'
    | '/products/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products/add'
    | '/products'
    | '/products/details/$id'
    | '/products/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/products'
    | '/products/add'
    | '/products/'
    | '/products/details/$id'
    | '/products/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsRouteRoute: typeof ProductsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/add': {
      id: '/products/add'
      path: '/add'
      fullPath: '/products/add'
      preLoaderRoute: typeof ProductsAddRouteRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/edit/$id': {
      id: '/products/edit/$id'
      path: '/edit/$id'
      fullPath: '/products/edit/$id'
      preLoaderRoute: typeof ProductsEditIdRouteRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/details/$id': {
      id: '/products/details/$id'
      path: '/details/$id'
      fullPath: '/products/details/$id'
      preLoaderRoute: typeof ProductsDetailsIdRouteRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
  }
}

interface ProductsRouteRouteChildren {
  ProductsAddRouteRoute: typeof ProductsAddRouteRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsDetailsIdRouteRoute: typeof ProductsDetailsIdRouteRoute
  ProductsEditIdRouteRoute: typeof ProductsEditIdRouteRoute
}

const ProductsRouteRouteChildren: ProductsRouteRouteChildren = {
  ProductsAddRouteRoute: ProductsAddRouteRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsDetailsIdRouteRoute: ProductsDetailsIdRouteRoute,
  ProductsEditIdRouteRoute: ProductsEditIdRouteRoute,
}

const ProductsRouteRouteWithChildren = ProductsRouteRoute._addFileChildren(
  ProductsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsRouteRoute: ProductsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
